# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClicApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClicApp
  pod 'Parse'
  pod 'AlamofireImage'
  pod 'MessageInputBar'
  pod 'GoogleSignIn'
  pod 'GoogleSignInSwiftSupport'
  # done

  target 'ClicAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClicAppUITests' do
    # Pods for testing
  end

end